config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :events
  root "sessions#new"
  get "signup", to: "user#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  post "auto", to: "sessions#create", as: "auto"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  scope :upcomming, -> { where('event_date > ?', Date.today) }
  scope :previews, -> { where('event_date < ?', Date.today) }

  belongs_to :creator, class_name: 'User'
  has_many :event_attending, foreign_key: 'attended_event_id'
  has_many :attendee, through: :event_attending, source: :event_attendee

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :description, presence: true, length: { minimum: 3, maximum: 1000 }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :event_attendee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  def already_attending?(event)
    attended_event.include? event
  end
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :event_attending, foreign_key: 'event_attendee_id'
  has_many :attended_event, through: :event_attending

  validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @user = User.find(session[:user_id])
    @event = @user.created_events.build(event_params)

    if @event.save
      redirect_to user_path(@event.creator)
    else
      render :new
    end
  end

  def index
    @user = User.find(session[:user_id])
    @upcomming_events = Event.upcomming
    @past_events = Event.previews
  end

  def show
    @event = Event.find(params[:id])

    @attend = @event.attendee
  end

  def edit
    @event = Event.find(params[:id])
    @add_attend = EventAttending.new
    @add_attend.attended_event_id = @event.id
    @add_attend.event_attendee_id = session[:user_id]
    if @add_attend.save
      redirect_to events_path
    else
      redirect_to root_url
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :event_date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_username(params[:username])
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def show
    @event = User.find(params[:id]).created_events
    @attend = User.find(params[:id]).attended_event
    @upcomming_events = @event.upcomming
    @past_events = @event.previews
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    !session[:user_id].nil? ? User.find(session[:user_id]) : nil
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def attendance_button(event)
    return if !current_user || current_user.already_attending?(event)

    link_to 'attend this event', edit_event_path(event.id)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<%= render "/shared/show_event" %>

app/views/events/new.html.erb
<%= form_with model: @event do |f| %>
<%= f.label "name: ",:Event_Name %>
<%= f.text_field :name %><br><br>
<%= f.label "event_date: ",:Event_Date %>
<%= f.date_field :event_date %><br><br>
<%= f.label "description: ",:Description %>
<%= f.text_field :description %><br><br>
<%= f.submit "Create" %>
<%end%>

app/views/events/show.html.erb
<h2>
    <%= @event.name %>
</h2>
<h4>Atendees</h4>
<% @attend.each do |t| %>
    <div>
        <%= "- " + t.username %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if(session[:user_id]) %>
      <strong><%= User.find(session[:user_id]).username%></strong> is logged in
     

      <%= link_to "log out", logout_path%> |
 
      <%= link_to  "Create Event", new_event_path %> |
      
      <%= link_to  "Go to events", events_path %>
    <% else %>
      <%= link_to  "Register", new_user_path   %>
    <% end %>
    <br>
      <br>
    <%= yield %>
    

 
  </body>
</html>

app/views/shared/_show_event.html.erb
<h2>UPCOMING EVENTS</h2>

<%@upcomming_events.each do |t|%>
<h3>
   Event: <%= link_to t.name, event_path(t) %>
</h3>
<span>
  Description: <%= t.description %>
</span>
<br><br>
<span>
  date: <%= t.event_date %>
</span>
<br>
<br>
<strong>author: <%= t.creator.username %></strong>

<%= attendance_button(t) %>

<hr>

<%end%><br>

<h2>PREVIEWSLY ATTENDED EVENTS</h2>
<%@past_events.each do |t|%>
<h3>
   Event: <%= link_to t.name, event_path(t) %>
</h3>
<span>
  Description: <%= t.description %>
</span>
<br><br>
<span>
  date: <%= t.event_date %>
</span>
<br>
<br>
<strong>author: <%= t.creator.username %></strong>

<% if(session[:user_id] && !t.attendee.include?(User.find(session[:user_id])) && t.creator.id != session[:user_id] ) %>
  <%= link_to "attend this event", edit_event_path(t.id) %>
<% end %>

<hr>

<%end%><br>

app/views/users/new.html.erb
<h2>Register</h2>
<%= form_with model: @user do |f| %>
    <%= f.label "username: ",:username %>
    <%= f.text_field :username %>
    <%= f.submit "Create" %>
<%end%>

app/views/users/show.html.erb
<h2>Events created</h2>
<%= render "shared/show_event" %>

<h3>Events attending</h3>
<ul>
<% @attend.each do |t| %>
    <li><%=link_to t.name, event_path(t) %></li> 
<% end %>
</ul>